version: '3'

networks:
  laravel:

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: laravel_nginx
    tty: true
    ports:
    - "8080:80"
    volumes:
    - ./../src:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: library/mysql:5.7.22
    container_name: laravel_mysql
    restart: unless-stopped
    tty: true
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
    - ./../src:/var/www
    ports:
    - "9000:9000"
    networks:
      - laravel
